### ISSUE TITLE
Deploying via Shell Scripts does not set the POSTGRES_ADMIN_LOGIN_PASS

### ISSUE THREAD

**Issue by ShaneOsborne** [Azure/Azure-Orbital-Analytics-Samples#72]
Running setup.sh or install.sh does not prompt the user for the admin password for PGSQL as described in the deployment documentation.

Without this $POSTGRES_ADMIN_LOGIN_PASS is empty and deployment will fail saying 

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"PasswordNotComplex","message":"Password validation failed. The password does not meet policy requirements because it is not complex enough."}]}

Thanks

**Comment by sjyang18** [comment]
We are setting postgresAdminLoginPass if is not passed, and stored in keyvault as follows: 
```
var postgresAdminLoginPassVar = empty(postgresAdminLoginPass) ? '${uniqueString(resourceGroup().id)}!' : postgresAdminLoginPass
```

Not sure what causes this problem. Do you have any suggestion?  Do you think if we change like below, it will resolve the issue you see?
```
uniqueString(resourceGroup().id, deployment().name)
```

**Comment by sjyang18** [comment]
@ShaneOsborne Would you share your bicep version for debugging? Mine is 0.6.1 and it was picking up the uniqueString function and a random password. 

```
az bicep version
# to upgrade bicep
# az bicep upgrade
```

**Comment by sjyang18** [comment]
@ShaneOsborne  This seems to be taken care of changes in install.sh. install_sh would pass empty postgres admin password, which will generate the postgres password.  Please get the latest main branch. I will close the issue for now. But, welcome to reopen.
